### Get na /api/cron
GET http://localhost:3000/api/cron

### POST na /api/cron
POST http://localhost:3000/api/cron
Content-Type: application/json

{
  "id_recorrencia": 6,
  "data_semana": ["4"],
  "horario_agendamento": ["17:05", "17:35"],
  "data_limite": "2024-11-15T03:00:00.000Z",
  "fk_id_pedido": 896
}

### POST na /api/cron
POST https://cafe-no-ponto.vercel.app/api/cron
Content-Type: application/json

{
  "id_recorrencia": 6,
  "data_semana": ["4"],
  "horario_agendamento": ["16:45"],
  "data_limite": "2024-11-16T03:00:00.000Z",
  "fk_id_pedido": 896
}

### DELETE cron
DELETE http://localhost:3000/api/cron
Content-Type: application/json

{
   "id_recorrencia": "2"
}