### Get na /api/cron
GET http://localhost:3000/api/cron

### POST na /api/cron
POST http://localhost:3000/api/cron
Content-Type: application/json

{
  "id_recorrencia": 6,
  "data_semana": ["1", "3"],
  "horario_agendamento": ["10:00", "03:00"],
  "data_limite": "2023-12-01T03:00:00.000Z",
  "fk_id_pedido": 896
}

### DELETE cron
DELETE http://localhost:3000/api/cron
Content-Type: application/json

{
   "id_recorrencia": "2"
}